server:
  port: 8090

# 分组任务配置
chatbot-api:
  launchList: group01,group02 # 启动几组，就配置几组
  group01:
    groupName: 我的朋友们
    groupId: 88858554122822 # 知识星球ID
    cookie: zsxq_access_token=A79DE3C0-28FA-CB1C-FA65-FCCDAC408DE2_B6F6C892B1FCA2F5; zsxqsessionid=7c7e5133f6f059628089407f542fcda2; UM_distinctid=185f8800f51370-0bc3b8e983e156-26021051-144000-185f8800f5232f; sensorsdata2015jssdkcross={"distinct_id":"421144142281228","first_id":"185f141e0ef60a-00cac363853b7cd-26021051-1327104-185f141e0f0476","props":{"$latest_traffic_source_type":"直接流量","$latest_search_keyword":"未取到值_直接打开","$latest_referrer":""},"identities":"eyIkaWRlbnRpdHlfY29va2llX2lkIjoiMTg1ZjE0MWUwZWY2MGEtMDBjYWMzNjM4NTNiN2NkLTI2MDIxMDUxLTEzMjcxMDQtMTg1ZjE0MWUwZjA0NzYiLCIkaWRlbnRpdHlfbG9naW5faWQiOiI0MjExNDQxNDIyODEyMjgifQ==","history_login_id":{"name":"$identity_login_id","value":"421144142281228"},"$device_id":"185f141e0ef60a-00cac363853b7cd-26021051-1327104-185f141e0f0476"}; abtest_env=product # 知识星球个人cookie信息
    openAiKey: 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 # 自行申请 https://beta.openai.com/overview 或者联系小傅哥 fustack 付费申请【购买虚拟号码等需要支付】。
    cronExpression: 0/30 * * * * ? # 执行的频次配置，参考：cron.qqe2.com
    silenced: false
#  group02:
#    groupName: 码农会锁
#    groupId: 28885518425541 # 知识星球ID
#    cookie:  # 知识星球个人cookie信息
#    openAiKey:  # 自行申请 https://beta.openai.com/overview 或者联系小傅哥 fustack 付费申请【购买虚拟号码等需要支付】。
#    cronExpression: 0/30 * * * * ? # 执行的频次配置，参考：cron.qqe2.com
#    silenced: true